package com.cooksys.facebook.model;

// Generated May 29, 2015 12:10:16 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Follower generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Follower implements java.io.Serializable {

	private Integer followerId;
	private User userByFriendId;
	private User userByUserId;
	private boolean isApproved;
	private boolean isBlacklisted;
	private Date lastUpdate;

	public Follower() {
	}

	public Follower(User userByFriendId, User userByUserId) {
		this.userByFriendId = userByFriendId;
		this.userByUserId = userByUserId;
	}
	
	public Follower(User userByFriendId, User userByUserId, boolean isApproved,
			boolean isBlacklisted, Date lastUpdate) {
		this.userByFriendId = userByFriendId;
		this.userByUserId = userByUserId;
		this.isApproved = isApproved;
		this.isBlacklisted = isBlacklisted;
		this.lastUpdate = lastUpdate;
	}

	public Integer getFollowerId() {
		return this.followerId;
	}

	public void setFollowerId(Integer followerId) {
		this.followerId = followerId;
	}

	public User getUserByFriendId() {
		return this.userByFriendId;
	}

	public void setUserByFriendId(User userByFriendId) {
		this.userByFriendId = userByFriendId;
	}

	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	public boolean isIsApproved() {
		return this.isApproved;
	}

	public void setIsApproved(boolean isApproved) {
		this.isApproved = isApproved;
	}

	public boolean isIsBlacklisted() {
		return this.isBlacklisted;
	}

	public void setIsBlacklisted(boolean isBlacklisted) {
		this.isBlacklisted = isBlacklisted;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
