package com.cooksys.facebook.model;

// Generated May 29, 2015 12:10:16 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Group generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Group implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private String description;
	private Date lastUpdate;
	private Set groupUsers = new HashSet(0);

	public Group() {
	}
	
	public Group(String name, String description, Date lastUpdate) {
		this.name = name;
		this.description = description;
		this.lastUpdate = lastUpdate;
	}

	public Group(String name, String description, Date lastUpdate,
			Set groupUsers) {
		this.name = name;
		this.description = description;
		this.lastUpdate = lastUpdate;
		this.groupUsers = groupUsers;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getGroupUsers() {
		return this.groupUsers;
	}

	public void setGroupUsers(Set groupUsers) {
		this.groupUsers = groupUsers;
	}

}
