package com.cooksys.facebook.model;

// Generated May 29, 2015 12:10:16 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Message generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Message implements java.io.Serializable {

	private Integer messageId;
	private User user;
	private String message;
	private String attachment;
	private boolean isRoot;
	private Boolean isChat;
	private Date lastUpdate;
	@XmlTransient
	private Set responsesForMessageId = new HashSet(0);
	@XmlTransient
	private Set responsesForRootId = new HashSet(0);
	@XmlTransient
	private Set tags = new HashSet(0);

	public Message() {
	}

	public Message(User user, String message, boolean isRoot, Date lastUpdate) {
		this.user = user;
		this.message = message;
		this.isRoot = isRoot;
		this.lastUpdate = lastUpdate;
	}

	public Message(User user, String message, String attachment,
			boolean isRoot, Boolean isChat, Date lastUpdate,
			Set responsesForMessageId, Set responsesForRootId, Set tags) {
		this.user = user;
		this.message = message;
		this.attachment = attachment;
		this.isRoot = isRoot;
		this.isChat = isChat;
		this.lastUpdate = lastUpdate;
		this.responsesForMessageId = responsesForMessageId;
		this.responsesForRootId = responsesForRootId;
		this.tags = tags;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	public boolean isIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(boolean isRoot) {
		this.isRoot = isRoot;
	}

	public Boolean getIsChat() {
		return this.isChat;
	}

	public void setIsChat(Boolean isChat) {
		this.isChat = isChat;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getResponsesForMessageId() {
		return this.responsesForMessageId;
	}

	public void setResponsesForMessageId(Set responsesForMessageId) {
		this.responsesForMessageId = responsesForMessageId;
	}

	public Set getResponsesForRootId() {
		return this.responsesForRootId;
	}

	public void setResponsesForRootId(Set responsesForRootId) {
		this.responsesForRootId = responsesForRootId;
	}

	public Set getTags() {
		return this.tags;
	}

	public void setTags(Set tags) {
		this.tags = tags;
	}

}
