package com.cooksys.facebook.model;

// Generated May 29, 2015 12:10:16 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * User generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class User implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String firstName;
	private String lastName;
	private String password;
	@XmlTransient
	private String salt;
	private String city;
	private String state;
	private Boolean isPrivate;
	private String school;
	private String relationshipStatus;
	private Date lastUpdate;
	@XmlTransient
	private Set followersForFriendId = new HashSet(0);
	@XmlTransient
	private Set groupUsers = new HashSet(0);
	@XmlTransient
	private Set followersForUserId = new HashSet(0);
	@XmlTransient
	private Set messages = new HashSet(0);
	@XmlTransient
	private Set tags = new HashSet(0);

	public User() {
	}

	private String name;

	public String getName() {
		return this.firstName + " " + this.lastName;
	}
	
	public User(String email, String firstName, String lastName,
			String password, Date lastUpdate) {
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.lastUpdate = lastUpdate;
	}

	public User(String email, String firstName, String lastName,
			String password, String salt, String city, String state,
			Boolean isPrivate, String school, String relationshipStatus,
			Date lastUpdate, Set followersForFriendId, Set groupUsers,
			Set followersForUserId, Set messages, Set tags) {
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.salt = salt;
		this.city = city;
		this.state = state;
		this.isPrivate = isPrivate;
		this.school = school;
		this.relationshipStatus = relationshipStatus;
		this.lastUpdate = lastUpdate;
		this.followersForFriendId = followersForFriendId;
		this.groupUsers = groupUsers;
		this.followersForUserId = followersForUserId;
		this.messages = messages;
		this.tags = tags;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Boolean getIsPrivate() {
		return this.isPrivate;
	}

	public void setIsPrivate(Boolean isPrivate) {
		this.isPrivate = isPrivate;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getRelationshipStatus() {
		return this.relationshipStatus;
	}

	public void setRelationshipStatus(String relationshipStatus) {
		this.relationshipStatus = relationshipStatus;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getFollowersForFriendId() {
		return this.followersForFriendId;
	}

	public void setFollowersForFriendId(Set followersForFriendId) {
		this.followersForFriendId = followersForFriendId;
	}

	public Set getGroupUsers() {
		return this.groupUsers;
	}

	public void setGroupUsers(Set groupUsers) {
		this.groupUsers = groupUsers;
	}

	public Set getFollowersForUserId() {
		return this.followersForUserId;
	}

	public void setFollowersForUserId(Set followersForUserId) {
		this.followersForUserId = followersForUserId;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

	public Set getTags() {
		return this.tags;
	}

	public void setTags(Set tags) {
		this.tags = tags;
	}

}
